
-
  branches:
    only:
      - release
  
  version: 5.6.{build}
  configuration: Release
  
  image: Visual Studio 2017

  install: 
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  
  before_build: 
    - cmd: nuget restore RefactoringEssentials\RefactoringEssentials.csproj
    - cmd: nuget restore RefactoringEssentials.sln

  build:
    project: RefactoringEssentials.sln

  after_test:
    - cmd: nuget pack bin\Release\RefactoringEssentials.nuspec -NoPackageAnalysis -BasePath bin\Release -OutputDirectory bin\Release
    - cmd: nuget pack bin\Release\RefactoringEssentials.Library.nuspec -NoPackageAnalysis -BasePath bin\Release -OutputDirectory bin\Release
  
  artifacts:
    - path: bin\**\*.nupkg
      name: NuGet
  
    - path: bin\**\*.vsix
      name: VSIX

-
  branches:
    only:
      - master
  
  version: 5.6.{build}
  configuration: Release
  
  image: Visual Studio 2017
  
  install: 
    - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  
  before_build: 
    - ps: Vsix-IncrementVsixVersion ".\Vsix\source.extension.vsixmanifest" | Vsix-UpdateBuildVersion
    - cmd: nuget restore RefactoringEssentials\RefactoringEssentials.csproj
    - cmd: nuget restore RefactoringEssentials.sln
  
  build:
    project: RefactoringEssentials.sln
  
  after_test:
    - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
 
